# generic_hw_control_loop:
#   loop_hz: 300
#   cycle_time_error_threshold: 0.01
# # Settings for ros_control hardware interface
# hardware_interface:
#   joints:
#     - Model_Rotation
#     - Rotation_Base
#     - Base_Elbow
#     - Elbow_Wrist
#     # - panda_finger_joint1
#   sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS

hardware_interface:
  joints:
    - Model_Rotation
    - Rotation_Base
    - Base_Elbow
    - Elbow_Wrist
owi535:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # arm_controller:
  #   type: effort_controllers/JointTrajectoryController
  #   joints:
  #     - Model_Rotation
  #     - Rotation_Base
  #     - Base_Elbow
  #     - Elbow_Wrist
  #   gains:
  #      Model_Rotation: { p: 12000, d: 1, i: 0.0, i_clamp: 10000 }
  #      Rotation_Base: { p: 30000, d: 1, i: 0.02, i_clamp: 10000 }
  #      Base_Elbow: { p: 18000, d: 1, i: 0.01, i_clamp: 1 }
  #      Elbow_Wrist: { p: 18000, d: 1, i: 0.01, i_clamp: 10000 }

  #   constraints:
  #     goal_time: 2.0

  #   state_publish_rate: 25

  #   controller_list:
  #    - name: arm_controller
  #      action_ns: follow_joint_trajectory
  #      default: True
  #      type: FollowJointTrajectory
  #      joints:
  #      - Model_Rotation
  #      - Rotation_Base
  #      - Base_Elbow
  #      - Elbow_Wrist
    # gains:
    #   panda_joint1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
    #   panda_joint2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
    #   panda_joint3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
    #   panda_joint4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
    #   panda_joint5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
    #   panda_joint6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
    #   panda_joint7: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }

    
  Model_Rotation_Position_Controller:
    type: position_controllers/JointPositionController
    joint: Model_Rotation   
    # pid: { p: 12000, i: 0.01, d: 10 }
  Rotation_Base_Position_Controller:
    type: position_controllers/JointPositionController
    joint: Rotation_Base  
    # pid: { p: 12000, i: 0.01, d: 10 }
  Base_Elbow_Position_Controller:
    type: position_controllers/JointPositionController
    joint: Base_Elbow 
    # pid: { p: 12000, i: 0.01, d: 10 }
  Elbow_Wrist_Position_Controller:
    type: position_controllers/JointPositionController
    joint: Elbow_Wrist   
    # pid: { p: 12000, i: 0.01, d: 10 }




  #   constraints:
  #     goal_time: 2.0

  #   state_publish_rate: 25

  
